### ISSUE TITLE
Add a before and after screenshot?

### ISSUE THREAD

**Issue by orta** [zhzhy/cocoapods-generator#1]
This would help show what the command does, I had to check the source code :+1:

**Comment by zhzhy** [comment]
@orta 
Before:
<img width="1116" alt="2016-03-03 7 42 33" src="https://cloud.githubusercontent.com/assets/1874817/13493463/38565f34-e179-11e5-849a-c1199386a655.png">
After:
<img width="1106" alt="2016-03-03 7 41 01" src="https://cloud.githubusercontent.com/assets/1874817/13493471/47093286-e179-11e5-9f19-07d71501e8cd.png">

**Comment by orta** [comment]
Perfect! Get that in the README :dancers:

**Comment by zhzhy** [comment]
@orta 
okay

**Comment by orta** [comment]
ace
